config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout' }
  resources :users
  resources :products do
    resources :comments
  end
  resources :orders, only: %i[index show create destroy]

  get 'static_pages/about'

  get 'static_pages/contact'

  get 'static_pages/index'

  get 'static_pages/landing_page'

  post 'static_pages/thank_you'

  post 'payments/create'

  root 'products#index'

end

app/views/shared/_footer.html.erb
<footer class="container-fluid">
    <div class="footer">
      &copy Voracious Vinyls 2016
    </div><!--end footer-->  
  </footer>

app/views/shared/_navbar.html.erb
<div class="container">
  <div class="navbar transparent navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <nav class="navbar-header navbar-inner">
          <button type="button" class="navbar-toggle"  data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <div class="nav navbar-nav navbar-brand">
            <%= link_to "VoVi", products_url %>
          </div><!--end projectname-->
        </nav><!--end nav header-->
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li>
              <% if user_signed_in? %>
                <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
              <% else %>
                <%= link_to('Login', new_user_session_path) %>
              <% end %>
            </li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Our Story", static_pages_about_url %></li>
            <li><%= link_to "Browse Records", products_url %></li>
            <li><%= link_to "Orders", orders_url %></li>
            <li><%= link_to "Contact", static_pages_contact_url %></li>
            <li>
              <div class="form-group">
                <%= form_tag("/products", method: "get", class: 'navbar-form', role: 'search') do %>
                <%= text_field_tag(:q, "", placeholder: "Search", class: "form-control" ) %>
                <%= submit_tag("Search", class: "btn btn-default") %>
                <% end %>
              </div>
            </li>
          </ul>
        </div><!--end nav collapse-->
      </div><!--end container-->
    </div><!--end navbar-->
  </div><!--end container-->

app/views/shared/_stripe_checkout_button.html.erb
<script
  src="https://checkout.stripe.com/checkout.js" class="stripe-button"
  data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
  data-image="/square-image.png"
  data-name="<%= @product.name %>"
  data-description="<%= @product.description %>"
  data-amount="<%= @product.price %>">
</script>